### ISSUE TITLE
minecraft crashed

### ISSUE THREAD

**Issue by andrewq99** [NicosaurusRex99/JARMGit#11]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2018-07-03 01:44:05 EDT
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at naturix.jarm.world.ModWorldGeneration.addOreSpawn(ModWorldGeneration.java:42)
    at naturix.jarm.world.ModWorldGeneration.genSurface(ModWorldGeneration.java:104)
    at naturix.jarm.world.ModWorldGeneration.generate(ModWorldGeneration.java:32)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1018)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:997)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:142)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 440811608 bytes (420 MB) / 889192448 bytes (848 MB) up to 1073741824 bytes (1024 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 89
  FML: MCP 9.42 Powered by Forge 14.23.4.2725 34 mods loaded, 34 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                     | Version           | Source                                | Signature                                |
       |:--------- |:---------------------- |:----------------- |:------------------------------------- |:---------------------------------------- |
       | UCHIJAAAA | minecraft              | 1.12.2            | minecraft.jar                         | None                                     |
       | UCHIJAAAA | mcp                    | 9.42              | minecraft.jar                         | None                                     |
       | UCHIJAAAA | FML                    | 8.0.99.99         | forge-1.12.2-14.23.4.2725.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                  | 14.23.4.2725      | forge-1.12.2-14.23.4.2725.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | chameleon              | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar              | None                                     |
       | UCHIJAAAA | orespawn               | 3.3.0             | OreSpawn-1.12-3.3.0.136.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | densemetals            | 1.2.0             | DenseMetals-1.12-1.2.0.20.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | silentlib              | 2.3.1             | SilentLib-1.12.2-2.3.1-107.jar        | None                                     |
       | UCHIJAAAA | funores                | 1.5.7             | FunOres-1.12-1.5.7-118.jar            | None                                     |
       | UCHIJAAAA | hardcoreore            | 0.2.0             | hardcoreore-1.12.2-0.2.0.jar          | None                                     |
       | UCHIJAAAA | jarm                   | 1.12.2.17b        | jarm-1.12.2.17b.jar                   | None                                     |
       | UCHIJAAAA | jei                    | 4.9.1.175         | jei_1.12.2-4.9.1.175.jar              | None                                     |
       | UCHIJAAAA | bop                    | 1.0               | MoreOres-1.0.1.jar                    | None                                     |
       | UCHIJAAAA | powerinventory         | 2.3.1             | OverpoweredInventory-1.12-2.3.1.jar   | None                                     |
       | UCHIJAAAA | simplecore             | 1.6.0.6           | simplecore-1.12.2-1.6.0.6.jar         | None                                     |
       | UCHIJAAAA | simpleores             | 1.11.1.9          | simpleores-1.12.2-1.11.1.9.jar        | None                                     |
       | UCHIJAAAA | storagedrawers         | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.6.jar       | None                                     |
       | UCHIJAAAA | superminer_core        | 2.6.34.336        | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_captivator  | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_cropinator  | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_excavator   | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_illuminator | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_lumbinator  | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_shaftanator | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_substitutor | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superminer_veinator    | [1.12]-2.6.34.336 | SuperMiner-2.6.34.336.jar             | None                                     |
       | UCHIJAAAA | superores              | 1.8.4_1.12        | superores-1.8.4_1.12.jar              | None                                     |
       | UCHIJAAAA | techores               | 1.1               | Tech+Ores+1.1+[1.12.2].jar            | None                                     |
       | UCHIJAAAA | terracore              | 2.1.12            | TerraCore-1.12-2.1.12.jar             | None                                     |
       | UCHIJAAAA | theoneprobe            | 1.4.22            | theoneprobe-1.12-1.4.22.jar           | None                                     |
       | UCHIJAAAA | vanillafix             | 1.0.9-97          | VanillaFix-1.0.9-97.jar               | None                                     |
       | UCHIJAAAA | veinminer              | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar | None                                     |
       | UCHIJAAAA | veinminermodsupport    | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar | None                                     |
       | UCHIJAAAA | xaerominimap           | 1.15.2            | Xaeros_Minimap_1.15.2_Forge_1.12.jar  | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Just Another Ruby Mod (jarm)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 2

**Comment by NicosaurusRex99** [comment]
I am going to write a "fix" that says if the number is negative spawn it at the maximum height

**Comment by NicosaurusRex99** [comment]
Fixed *hopefully* 62c25ee
