### ISSUE TITLE
missing ore

### ISSUE THREAD

**Issue by beesyndicate** [NicosaurusRex99/JARMGit#2]
Is seems that there isnt any ruby ore spawningall the items are in JRE but when i try to spawn them in it says the items do not exist

**Comment by NicosaurusRex99** [comment]
1 please send me your seed.
2 What version

**Comment by beesyndicate** [comment]
version 1.12.2 
Seed: -7226055637873713691


![1](https://user-images.githubusercontent.com/32340677/30967595-cbb8f03c-a42a-11e7-904e-ece6aea9e05c.png)
![2](https://user-images.githubusercontent.com/32340677/30967621-e45922e2-a42a-11e7-9493-7c10821deff0.png)
[latest.log](https://github.com/NicosaurusRex99/JARMGit/files/1340901/latest.log)

**Comment by beesyndicate** [comment]
My problem was caused by a Forge configuration problem. You may want to add that this mod requires forge under a requirements section on the project front page. I can now spawn in the items but I still am not able to locate any ruby ore in my world i made a new seed 2428299609187039

**Comment by beesyndicate** [comment]
NM finally found some can I adjust the spawn rate ?

**Comment by NicosaurusRex99** [comment]
@beesyndicate in the 1.12.2.3 version you can adjust the spawn rate, but it is rarer because it is stronger than diamond
