### ISSUE TITLE
Add Ruby hammer

### ISSUE THREAD

**Issue by beesyndicate** [NicosaurusRex99/JARMGit#4]
NicosaurusRex99, 

Below is my feature request:

Please add a Ruby hammer to JARM!

These hammers would complement the hammers from Thermal Foundation
Hammers mine a 3x3 area 
The recipe would consist of sticks and rubys  see below 

R R R
* s *
* s * 

Please see 
https://teamcofh.com/docs/hammers/ 
for more details. 

Pleases and thank you
Much LURV from the MittzFitz

**Comment by NicosaurusRex99** [comment]
And Amethyst

**Comment by NicosaurusRex99** [comment]
Added bc222bb (will push soonish) @beesyndicate Will push update after i fix a minor bug i discovered

**Comment by NicosaurusRex99** [comment]
![2018-03-09_15 44 08](https://user-images.githubusercontent.com/11579935/37191639-cfba55c6-23b0-11e8-89e9-e5394b44a9d9.png)

**Comment by beesyndicate** [comment]
THIS IS AMAZEBALLS
