### ISSUE TITLE
A gift from me to you. 

### ISSUE THREAD

**Issue by beesyndicate** [NicosaurusRex99/JARMGit#5]
I cleaned up these up a little bit as a thank you for creating this addition so quickly 

http://beesyndicate.ddns.net:34/HammerPNGs.zip
[HammerPNGs.zip](https://github.com/NicosaurusRex99/JARMGit/files/1797051/HammerPNGs.zip)
both files are the same. I just put both links in case this site got funny about uploading Zips but I'm gussing Github would sort of have to be cool with them.

**Comment by NicosaurusRex99** [comment]
<3
