### ISSUE TITLE
how do i change ore spawn for all ore

### ISSUE THREAD

**Issue by andrewq99** [NicosaurusRex99/JARMGit#7]

**Comment by andrewq99** [comment]
because all our ore are spawn to low

**Comment by NicosaurusRex99** [comment]
mod directory>config>naturix>just another ruby mod. look through the settings, not yet finished implementing all configurable heights but most are there

**Comment by andrewq99** [comment]
i look in the config folder you only have confg for 2 ore. i want confg for all the ore

**Comment by NicosaurusRex99** [comment]
As previously mentioned not all implemented as of yet, it is in the works. i am just dealing with a server side crash at the moment

**Comment by NicosaurusRex99** [comment]
I tell you what. im tired of getting no where with this server bug atm. ill make this priority 1

**Comment by andrewq99** [comment]
thank you

**Comment by NicosaurusRex99** [comment]
Fixed in ac72720
