### ISSUE TITLE
tin and silver are not spawn in 

### ISSUE THREAD

**Issue by andrewq99** [NicosaurusRex99/JARMGit#9]
i made two worlds and couldn't find tin or silver am doing something wrong

**Comment by andrewq99** [comment]
# Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 90]
    I:tinMax=90

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:tinMin=1

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 30]
    I:tinTries=30
# Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 90]
    I:silverMax=90

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:silverMin=1

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 30]
    I:silverTries=30

**Comment by andrewq99** [comment]
# Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 90]
    I:silverMax=90

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:silverMin=1

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 30]
    I:silverTries=30

**Comment by andrewq99** [comment]
# Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 90]
    I:tinMax=90

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:tinMin=1

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 30]
    I:tinTries=30

**Comment by NicosaurusRex99** [comment]
Thank you for the report, just checked Just enough resources and you are right

**Comment by NicosaurusRex99** [comment]
Are your tin and silver modules off?

**Comment by NicosaurusRex99** [comment]
https://github.com/NicosaurusRex99/JARMGit/issues/10
Found likely cause. fixing now

**Comment by NicosaurusRex99** [comment]
Testing "fix"

**Comment by NicosaurusRex99** [comment]
Fixed c16caf1
